spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/na_manager
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: localhost
    port: 1025
    username: ""
    password: ""
    properties:
      mail:
        smtp:
          trust: "*"
        auth: true
        starttls:
          enable: false
        connectiontimeout: 5000
        timeout: 3000
        write-timeout: 5000

application:
  security:
    jwt:
      secret-key: 824485CF87AEBB1468767FA46ED17D9C4F55B6A7E1234567890ABCDEF1234567
      expiration: 8640000
  mailing:
    frontend:
      activation-url: http://localhost:4200/activate-account
server:
  port: 9090