spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/na_manager
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: localhost
    port: 1025
    username: ""
    password: ""
    properties:
      mail:
        smtp:
          trust: "*"
        auth: true
        starttls:
          enable: false
        connectiontimeout: 5000
        timeout: 3000
        write-timeout: 5000

application:
  security:
    jwt:
      secret-key: 824485CF87AEBB1468767FA46ED17D9C4F55B6A7E1234567890ABCDEF1234567
      expiration: 8640000
  mailing:
    frontend:
      activation-url: http://localhost:4200/activate-account
      password-reset-url: http://localhost:4200/reset-password
  frontend:
    external-login-url: http://localhost:4200/external-login
    password-reset-url: http://localhost:4200/reset-password
  accounts:
    data-directory: data

server:
  port: 9090

# Keycloak Configuration
keycloak:
  auth-server-url: http://localhost:8180
  realm: manager-realm
  resource: manager-app
  credentials:
    secret: BW7P6oGHgz36wHx6QD9Vtz7tWqoJOi4C
  admin-username: admin
  admin-password: admin
  public-client: false
  bearer-only: false
  use-resource-role-mappings: true
  ssl-required: external
  confidential-port: 0
  direct-access-grants-enabled: true

# Logging configuration
logging:
  level:
    com.na.manager.manager.keycloak: DEBUG
    org.keycloak: INFO
    javax.ws.rs: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
